import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {signIn, useSession, signOut} from "next-auth/react";
import { useEffect } from "react";

const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  const {data: session} = useSession();

  useEffect(() => {
    // Update the document title using the browser API
    document.title = `You clicked times`;
    console.log(session)
  });


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p onClick={() => signIn('google')}>
            SignIn Google
          </p>
          <p onClick={() => signIn('github')}>
            SignIn GIT
          </p>
          <p onClick={() => signIn()}>
            SignOUT
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
      </main>
    </>
  )
}
